spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        name: fundRaised_topic
      channel:
        search-appearance-channel:
          name: search-appearance-event
        bought-premium: bought_premium_channel
        recommendation: recommendation_channel
        like-analytics-topic: like_analytics
        projects_view_channel:
          name: projects_view_channel
        ad-bought-channel:
          name: ad_bought_channel

server:
  port: 8086

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

user-service:
  host: localhost
  port: 8080
